[dr]
type = drive
scope = drive
token = {"access_token":"REPLACE_WITH_YOUR_ACCESS_TOKEN","token_type":"Bearer","refresh_token":"REPLACE_WITH_YOUR_REFRESH_TOKEN","expiry":"2099-01-01T00:00:00.000000000+07:00"}
